annotations:
  shipitcli.com/config:
    commands:
      build: composer dump-autoload
    php_version: 8.3.29
    phpix: true
    phpix_worker_threads: 4
    port: 8080
    use_composer: true
  shipitcli.com/provider: php
  shipitcli.com/version: 0.21.5
app_id: da_R36ILtlUZX1P
enableDatabase: true
kind: wasmer.io/App.v0
name: eventx
owner: dimaljay
package: sha256:3e38dfb86b1f4a016ac35db787a42f3a3575836829b924581ac35670d6b4536a
scaling:
  mode: single_concurrency

volumes:
  - name: uploads
    mount: /uploads
